name: Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'devel'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build release
        run: |
          npm ci
          npm run release

      - name: Upload artifacts for devel branch
        if: github.ref == 'refs/heads/devel'
        uses: actions/upload-artifact@v4
        with:
          name: saka-key-artifacts
          path: |
            chrome-prod.zip
            firefox-prod.zip
            chrome-debug.zip
            firefox-debug.zip

      - name: Rename assets
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          mv chrome-prod.zip chrome-prod-${VERSION}.zip
          mv firefox-prod.zip firefox-prod-${VERSION}.zip
          mv chrome-debug.zip chrome-debug-${VERSION}.zip
          mv firefox-debug.zip firefox-debug-${VERSION}.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            chrome-prod-*.zip
            firefox-prod-*.zip
            chrome-debug-*.zip
            firefox-debug-*.zip
